### ISSUE TITLE
[1.2.4] Sound priority values above 255 cause exception

### ISSUE THREAD

**Issue by derekmd** [GitExl/WhackEd4#12]
1998's Twilight Warrior TC https://www.doomworld.com/idgames/levels/doom2/Ports/s-u/tw_11 was for Doom Legacy but AFAIK its twilight.deh is Doom 1.9 without BEX extras.

Opening twilight.deh using doom2.wad/1.9 mode with WhackEd4 v1.2.4 on Windows 10 (update 2004 not installed yet) causes an exception. Same when choosing Boom mode.

```
src\whacked4\ui\windows.py:233: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
src\whacked4\ui\windows.py:235: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
src\whacked4\ui\windows.py:237: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
src\whacked4\ui\windows.py:239: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
src\whacked4\ui\windows.py:241: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
src\whacked4\ui\windows.py:243: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
src\whacked4\ui\windows.py:245: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
src\whacked4\ui\windows.py:247: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
src\whacked4\ui\windows.py:249: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
src\whacked4\ui\windows.py:2273: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
src\whacked4\ui\windows.py:3522: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
src\whacked4\ui\windows.py:3524: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
src\whacked4\ui\windows.py:3936: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
src\whacked4\ui\windows.py:3938: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
Traceback (most recent call last):
  File "src\whacked4\app.py", line 68, in OnInit
  File "src\whacked4\ui\mainwindow.py", line 259, in open_file
  File "src\whacked4\ui\mainwindow.py", line 447, in update_ui
  File "src\whacked4\ui\editors\soundsframe.py", line 86, in build
  File "src\whacked4\ui\editors\soundsframe.py", line 119, in soundlist_build
  File "src\whacked4\ui\editors\soundsframe.py", line 152, in soundlist_update_row
IndexError: list index out of range
```

Ignoring unrelated deprecation messages, there seems to be an issue array dereferencing `SoundsFramehttps.priority_colours`? https://github.com/GitExl/WhackEd4/blob/334e9d5cb167627453d21730aafef4cbae05b03d/src/whacked4/ui/editors/soundsframe.py#L150-L152

I noticed https://www.doomworld.com/idgames/levels/doom2/a-c/allhell opens fine and it only has a single custom sound entry. twilight.deh has these six entries:

```
Sound 74
Value = 120

Sound 80
Value = 300

Sound 84
Value = 32

Sound 98
Value = 100

Sound 99
Value = 64

Sound 103
Value = 300
```

If I remove the bottom five, WhackEd4 can now open twilight.deh.

**Comment by GitExl** [comment]
That patch sets two of it's sound priorities to 300, while WhackEd never expects these to be above 255. Looking at the Doom source code though, using the full int range would be valid. I'll have to adjust the UI to allow this to happen.

**Comment by GitExl** [comment]
This has been fixed in the latest release. https://github.com/GitExl/WhackEd4/releases/tag/v1.3.0-beta
