### ISSUE TITLE
Crash on start up

### ISSUE THREAD

**Issue by cap44** [GitExl/WhackEd4#13]
WhackEd4 1.2.4 on Windows 10 2004.
Starting WhackEd4 results in a crash with the following output:
```
src\whacked4\ui\windows.py:233: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
src\whacked4\ui\windows.py:235: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
src\whacked4\ui\windows.py:237: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
src\whacked4\ui\windows.py:239: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
src\whacked4\ui\windows.py:241: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
src\whacked4\ui\windows.py:243: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
src\whacked4\ui\windows.py:245: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
src\whacked4\ui\windows.py:247: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
src\whacked4\ui\windows.py:249: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
Traceback (most recent call last):
  File "src\whacked4\app.py", line 60, in OnInit
  File "src\whacked4\ui\mainwindow.py", line 54, in __init__
  File "src\whacked4\ui\editors\statesframe.py", line 63, in __init__
  File "src\whacked4\ui\windows.py", line 1942, in __init__
  File "src\whacked4\ui\spritepreview.py", line 35, in __init__
wx._core.wxAssertionError: C++ assertion "strcmp(setlocale(LC_ALL, NULL), "C") == 0" failed at ..\..\src\common\intl.cpp(1579) in wxLocale::GetInfo(): You probably called setlocale() directly instead of using wxLocale and now there is a mismatch between C/C++ and Windows locale.
Things are going to break, please only change locale by creating wxLocale objects to avoid this!
Traceback (most recent call last):
  File "src\whacked4\ui\editors\thingsframe.py", line 314, in activate
  File "src\whacked4\ui\editors\thingsframe.py", line 352, in update_properties
AttributeError: 'NoneType' object has no attribute 'things'
Traceback (most recent call last):
  File "src\whacked4\ui\editors\thingsframe.py", line 314, in activate
  File "src\whacked4\ui\editors\thingsframe.py", line 352, in update_properties
AttributeError: 'NoneType' object has no attribute 'things'

```
This happens with the portable 7zip archive and the installer.

**Comment by GitExl** [comment]
Does this modified version work?

- http://www.teamhellspawn.com/exl/whacked4/files/whacked4-setup-1.2.4-interim.exe for the installer
- http://www.teamhellspawn.com/exl/whacked4/files/whacked4-1.2.4-interim.7z for the archive.

**Comment by GitExl** [comment]
Does this still occur with the latest release https://github.com/GitExl/WhackEd4/releases/tag/v1.3.0-beta ?

**Comment by cap44** [comment]
Not that I am aware of, no
