### ISSUE TITLE
PermissionError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by TheParadoxBox** [GitExl/WhackEd4#17]
Whenever I try to open a file in WhackEd, it crashes with the following error:

```
src\whacked4\ui\windows.py:233: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
src\whacked4\ui\windows.py:235: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
src\whacked4\ui\windows.py:237: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
src\whacked4\ui\windows.py:239: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
src\whacked4\ui\windows.py:241: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
src\whacked4\ui\windows.py:243: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
src\whacked4\ui\windows.py:245: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
src\whacked4\ui\windows.py:247: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
src\whacked4\ui\windows.py:249: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
src\whacked4\ui\windows.py:2273: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
src\whacked4\ui\windows.py:3522: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
src\whacked4\ui\windows.py:3524: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
src\whacked4\ui\windows.py:3936: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
src\whacked4\ui\windows.py:3938: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
Traceback (most recent call last):
  File "src\whacked4\ui\mainwindow.py", line 765, in file_save
  File "src\whacked4\ui\mainwindow.py", line 405, in save_file
  File "src\whacked4\dehacked\patch.py", line 182, in write_dehacked
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\[censored]\\Downloads\\tower.deh'
```

This does not happen when I create a new file or open a file without an accompanying .WHACKED file, only when opening lone .DEHs or .BEXes or the like.

EDIT: Actually, it does happen when opening some files with .WHACKEDs. I'm currently looking into it further.

EDIT 2: Of all the DeHackEd patches I have, the only one afflicted by the bug is `accpstl.deh`, available on Doomworld. `m8f-text.deh` is also bugged, but by a different error:

```
src\whacked4\ui\windows.py:233: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
src\whacked4\ui\windows.py:235: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
src\whacked4\ui\windows.py:237: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
src\whacked4\ui\windows.py:239: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
src\whacked4\ui\windows.py:241: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
src\whacked4\ui\windows.py:243: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
src\whacked4\ui\windows.py:245: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
src\whacked4\ui\windows.py:247: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
src\whacked4\ui\windows.py:249: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
src\whacked4\ui\windows.py:2273: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
src\whacked4\ui\windows.py:3522: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
src\whacked4\ui\windows.py:3524: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
src\whacked4\ui\windows.py:3936: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
src\whacked4\ui\windows.py:3938: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
Traceback (most recent call last):
  File "src\whacked4\ui\mainwindow.py", line 765, in file_save
  File "src\whacked4\ui\mainwindow.py", line 405, in save_file
  File "src\whacked4\dehacked\patch.py", line 220, in write_dehacked
  File "src\whacked4\dehacked\patch.py", line 255, in write_patch_ext_strings
KeyError: 'GOTARMOR   '
```

This might be a mistake on m8f's part. I'm fairly new to DeHackEd, however, so I doubt myself on that last statement very much.

**Comment by GitExl** [comment]
accpstl.deh loads and saves fine here. An access denied error means that the user under which WhackEd is running doesn't have the permissions to open the file, or the file is already open in another program or process.

Do you have a link to m8f-text.deh (or the mod that it is a part of)?

**Comment by TheParadoxBox** [comment]
Sorry that I took so long to respond, didn't notice you replied. I don't know where/if there's an unmodified version, but a version for Back to Saturn X can be found here:
https://forum.zdoom.org/viewtopic.php?f=46&t=59373

**Comment by GitExl** [comment]
Closing this as it is an old issue, and patch parsing has changed. If the error still occurs, please open a new issue and provide a link to or upload the contents of the patch file in question.
