### ISSUE TITLE
Fatal error in WhackED4

### ISSUE THREAD

**Issue by Kras945** [GitExl/WhackEd4#43]
What is problem?
```
Traceback (most recent call last):
  File "C:\python38\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 40, in run
  File "C:\python38\lib\site-packages\cx_Freeze\initscripts\Console.py", line 32, in run
  File "src/main.py", line 18, in <module>
  File "src\whacked4\app.py", line 27, in __init__
  File "C:\python38\lib\site-packages\pyaudio.py", line 677, in __init__
OSError: [Errno -9986] Internal PortAudio error
```

**Comment by Kras945** [comment]
Oc: windows 10 
Earlier error not have, work good
