### ISSUE TITLE
Crash when trying to select PlaySound code pointer (on frame 1038)

### ISSUE THREAD

**Issue by AnotherLife** [GitExl/WhackEd4#9]
Traceback (most recent call last):
  File "src\whacked4\ui\editors\statesframe.py", line 671, in set_action
  File "src\whacked4\ui\editors\statesframe.py", line 494, in set_param_visibility
KeyError: 'name'

**Comment by GitExl** [comment]
The PlaySound action was missing a parameter name in the DoomRetro engine configuration. Fixed, thanks.
